### ISSUE TITLE
getting exception on iterator

### ISSUE THREAD

**Issue by avnerbarr** [stephencelis/SQLite.swift#1036]
getting a crash here when the DB is open in 2 processes:

```
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: database is locked (code: 5)
extension FailableIterator {
    public func next() -> Element? {
        return try! failableNext()
    }
}

// when iterating
for row in try db.prepare(...) {
        }
```

**Comment by juanjoseluisgarcia** [comment]
SQLite blocks the file when you access it. You need to keep a global reference to the connection to avoid this kind of issues. On another matter of things, this repo is abandoned. The Author is involved in some kind of online teaching courses and even though he has activity on other repos he seems to not have the courage to announce he will not be continuing with this one. My advice is that you switch to another library like GRDB.

**Comment by NathanFallet** [comment]
We merged a fix replacing the `try!` by a `try?`.

**Comment by tw0po1nt** [comment]
@NathanFallet I am still getting this issue on the latest release 0.14.1. It appears the `try?` [you mention](https://github.com/stephencelis/SQLite.swift/blob/7a2e3cd27de56f6d396e84f63beefd0267b55ccb/Sources/SQLite/Core/Statement.swift#L218) is still a `try!`, so this is still an issue.

**Comment by NathanFallet** [comment]
@tw0po1nt We reverted this fix; as explained in #1075, you should use `failableNext()` and handle the error by yourself using a `do`/`catch` block. We cannot provide a default behavior (e.g. return nil) when an error occurs, it's up to you to choose what you want to do.
