### ISSUE TITLE
Umbrella header SQLite.h not found in module.modulemap

### ISSUE THREAD

**Issue by arnoldschmid** [stephencelis/SQLite.swift#230]
I've updated XCode to the new version and I am trying to convert everything to use Swift 2.0. Unfortunately SQLite does not work anymore. I used the newest cocoapods (ver. 0.38.2) and i use this podfile:
use_frameworks!
pod 'SQLite.swift',git: 'https://github.com/stephencelis/SQLite.swift.git',branch: 'swift-2'
But I receive always the above mentioned error. I tried to clean the Build Folder without success, always the same. Using the old version of SQLite.swift (copying the project in my project) with the old version of xcode was running like a charm. Now I have troubles using SQLite.swift. 
thanks
arnold

**Comment by vineethvijayan** [comment]
@arnoldschmid  do u have the below issue

header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h"

??
I am also facing the same

**Comment by hohband** [comment]
Does anybody solve this problem? I have the same problem.

**Comment by stephencelis** [comment]
Can you try against the master branch again? I've merged the swift-2 branch in.

**Comment by warn4n** [comment]
We are still having this issue on the master branch. We had earlier failed to get it working with pods on Swift 1.2, so had fallen back to the manual installation instructions. We are really hoping to go the pods route now that we are upgrading our project to Swift 2. We think we thoroughly removed the previous manual installation, but I guess there is a chance this issue could be related to some ghost or remnant of that.

**Comment by stephencelis** [comment]
@warn4n Can you tell me where your Xcode.app is installed?

**Comment by warn4n** [comment]
It's in /Applications, updated from the Mac app store.

**Comment by coolgastjen** [comment]
I can confirm this problem. It happened after updating to Swift 2.
Xcode.App is also in the /Applications folder

**Comment by cliftonlabrum** [comment]
Did anyone figure this out? I just installed this today in Xcode 7.1.1 and I'm getting this same error.

**Comment by nickmshelley** [comment]
@cliftonlabrum I'm pretty sure the swift2 branch was merged into master and is out of date. We have this line in our podfile and it works fine: `pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'`

**Comment by cliftonlabrum** [comment]
That's what I have in my Podfile, too. Maybe something is wrong with my build settings in Xcode.

**Comment by Bronts** [comment]
I met same problem with this error : umbrella header "SQLite.h"
![image](https://cloud.githubusercontent.com/assets/3986255/11923844/4f06af14-a7e4-11e5-8ba4-fd9718928b21.png)
My cocoapods version is 0.39 Xcode7.2
I create a new project with cocoapod to integrate SQLite.swift. It builds well.
I have no idea to solve this error in project setting.

**Comment by Bronts** [comment]
Hi everyone.
I had solve this problem I met.
refer to https://forums.developer.apple.com/thread/7528
point out by TommieC of 4th
I Resolved all errors/warnings and then the project build success.

**Comment by Bronts** [comment]
I found I did't solve this error with cococapod.But When I solved this problem when try to build my project with carthage.
first, I met this error on my OSX thich is 10.11.3 beta.
and if you want to use Carthage. You should do with this https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by mikemee** [comment]
Hi all: please try the `publicpod` branch. It's just a simple one line change to your `Podfile` (or `Cartfile`) - see PR https://github.com/stephencelis/SQLite.swift/pull/314 for instructions. 

If you're just trying to get SQLite database access without encryption, it should fix all build problems as it's now a very vanilla build. (Per #311, the goal is to add SQLCipher via a separate build to keep things simpler).

And if any CocoaPods experts out there have an idea on how to fix the erroneous warning (`Umbrella header for module 'SQLite' does not include header 'fts3_tokenizer.h`), any help is much appreciated. _CocoaPods tends to trip over itself a little and in an effort to keep tweaking to a minimum, I gave up trying to remove this for now._

**Comment by iNoles** [comment]
@mikemee By looking to http://stackoverflow.com/questions/29657487/umbrella-header-for-module-bolts-does-not-include-header-bfapplinkresolving-h, You would need to add it on module map too.

**Comment by mikemee** [comment]
Thanks! Yes, I saw that article and tried it, but failed to find the right magic incantation. Xcode and hence Carthage are fine as is.  I'll try again to tweak the CocoaPods specific module map file again after this set of changes is confirmed - though hopefully someone will beat me to it 😎.

**Comment by mikemee** [comment]
This should now be fixed, via PR 314, version 0.9.0. This is now an 'official' CocoaPod and thus can be installed like any other. See updated installation instructions on the home page.

**Comment by gdelmas** [comment]
still getting the [error](https://github.com/stephencelis/SQLite.swift/issues/230#issuecomment-166204169) with version 0.9.2 and current XCode 7.2 (7C68)

**Comment by mikemee** [comment]
@gdelmas How are you integrating the library?  Carthage or CocoaPods or manually or ??

**Comment by gdelmas** [comment]
@mikemee cocoapods

**Comment by mikemee** [comment]
Hmm..  So that most likely means that the path in this file:

https://github.com/stephencelis/SQLite.swift/blob/master/podstuff/module.modulemap

which is current set to:

header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h"

is different for your machine...  Can you take a look and see if you can find it?  We might have to create a script for this, like the one used here: https://github.com/svdo/swift-netutils/tree/master/ifaddrs.

Btw, we can chat here https://gitter.im/stephencelis/SQLite.swift in case that's more convenient.

**Comment by mikemee** [comment]
Summarizing the chat we had:  When @gdelmas deleted the `module.modulemap` file from his CocoaPod install, everything started working....  V strange...  More research is needed clearly!  

Other data: this strategy worked with CocoaPods v1.0 beta 2.

**Comment by stephencelis** [comment]
@gdelmas Can you try the following Podfile with a brand new project?

``` rb
use_frameworks!

pod 'SQLite.swift', '~> 0.9.2'
```

I'd like to isolate the problem and see if it has to do with your existing project file or your computer. I've heard that certain project file setups can cause issues (_e.g._, overrides to certain build settings).

**Comment by gdelmas** [comment]
hi @stephencelis,

i could not reproduce the issue with a new project. i also tried to use the same Podfile from the other project, and it worked. i also tried to manually set a bridging header, as the other project uses. still no issue. if you have any other ideas what i might try to reproduce, please tell.

best,
gerard

**Comment by mikemee** [comment]
@gdelmas First, many thanks for trying this. That is hugely helpful!  (And I know it can be tedious to do!) 

Do you have a gut feel that perhaps this is "fixed" in the latest `SQLite.swift` release, but your original project retains some strangeness either from an earlier install or its own needs?  Or is that just typical wishful thinking on my part perhaps?

**Comment by gdelmas** [comment]
i just did have one pod in the other project and tried to install the SQLite pod and two other pods. the same configuration seems to work an the new project. although i installed the pods in another order. if this can be an issue i might retry that. apart from that i have no gut feel what might have caused the issue.

**Comment by peymankh** [comment]
@stephencelis @mikemee @gdelmas 
I have been facing the exact same issue as well, I bumped into this [question](http://stackoverflow.com/a/30355134/81388) on my search to resolve this, then it made me realise that my project file is not using **${inherited}** for **Header Search Paths** and **User Header Search Paths**, although **Always Search User Path** was set to **NO**. After changing them to use **${inherited}**, it all started working just as expected.

**Comment by jberkel** [comment]
probably out-of-date, closing

**Comment by volodg** [comment]
Happens again if remove `use_frameworks!`, cocoapods ver. 1.5.0
<img width="1137" alt="screen shot 2018-04-09 at 7 49 17 pm" src="https://user-images.githubusercontent.com/32120/38496211-364bb74e-3c2f-11e8-86c6-ff15e9d76996.png">

**Comment by unknown-account** [comment]
The same error without **use_frameworks!**

**Comment by peymankh** [comment]
@volodg Issue is with linking dynamic library of `libsqlite3.tbd`. I've made an issue in #831 to find a solution that should work for both Cocoapods and Carthage when building static.
