### ISSUE TITLE
SQLCipher - v4 does not read v3 files

### ISSUE THREAD

**Issue by Tybion** [stephencelis/SQLite.swift#908]
Xcode 10.1 currently being used
(but couldn't get things working on 10.2 either)

Test iPhones: (both fail)
**iPhone 5s** (iOS 10.3.3)
**iPhone 6** using simulator (iOS 12.1)

From pod install ..
**Using SQLCipher (4.1.0)
Using SQLite.swift (0.11.5)**

**database.key(key)** fails
   error='**file is not a database (code: 26)**'

My code - unchanged for over a year ..
```
do {
    try database = Connection(path, readonly: true)
    try database!.key(key)    // failing line - exec goes to Cipher.swift below ..
```
    
Cipher.swift ..
```
    //key is correct - defined as String
    //db is "main"

    public func key(_ key: String, db: String = "main") throws {
        try _key_v2(db: db, keyPointer: key, keySize: key.utf8.count) // goes to function below ..
    }

    :    :    

    // MARK: - private
    private func _key_v2(db: String, keyPointer: UnsafePointer<UInt8>, keySize: Int) throws {
        try check(sqlite3_key_v2(handle, db, keyPointer, Int32(keySize)))
        try cipher_key_check()  // goes to function below ..
    }

    :      :

    // When opening an existing database, sqlite3_key_v2 will not immediately throw an error if
    // the key provided is incorrect. To test that the database can be successfully opened with the
    // provided key, it is necessary to perform some operation on the database
    // (i.e. read from it).
    private func cipher_key_check() throws {
        try scalar("SELECT count(*) FROM sqlite_master;")  // this throws error
    }
```

**Comment by RuoG** [comment]
Hello，I have this problem。SQLCipher Can‘t be use！😂
<img width="657" alt="屏幕快照 2019-04-13 14 30 29" src="https://user-images.githubusercontent.com/49544632/56075661-badf9c00-5df8-11e9-8790-91a70495bf56.png">

**Comment by Tybion** [comment]
SQLCipher 4 does not read version 3 files by default.
https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/

I have fixed my problem by continuing to use SQLCipher 3 - this is in my Podfile
```
# Force SQLCipher to newest v3, so can read v3 files
pod 'SQLCipher', '3.4.2'
pod 'SQLite.swift/SQLCipher','~> 0.11.5'  
```

To read version 3 files using SQLCipher 4, set this pragma.
PRAGMA cipher_compatibility = 3;

I think you do this in Swift like so ..
```
try db.execute("PRAGMA cipher_compatibility = 3;")
```
Of course if you do this, then you do not benefit from newer version 4 performance and security benefits.

**Can we have SQLIte.swift apply this pragma if there is a key failure (and retry the key, and log a warning), to avoid breaking apps when they upgrade to SQLCipher version 4?**

**Comment by RuoG** [comment]
hello, This problem still exists。
<img width="464" alt="屏幕快照 2019-04-14 08 28 10" src="https://user-images.githubusercontent.com/49544632/56086699-41df5380-5e8f-11e9-8f29-13d5ecbbe695.png">

<img width="663" alt="屏幕快照 2019-04-14 08 26 46" src="https://user-images.githubusercontent.com/49544632/56086693-0fcdf180-5e8f-11e9-9235-f59c6fc71cdb.png">

**Comment by Tybion** [comment]
FYI, decided to try out SQLCipher 4.2.0 (Xcode 10.3, Swift 5) on a version 3 encrypted file.

Podfile ..
```
    # Allow the install of SQLCipher 4.2.0
    #pod 'SQLCipher', '3.4.2'
    pod 'SQLite.swift/SQLCipher','~> 0.12.2'  # needs Swift 5+, Xcode 10.2+
```
Code ..
```
   do {
            featureDB = try Connection(folder + "my.sqlite")
            
            // Read & write version 3 encryption (doesn't work) ..
            try featureDB.execute("PRAGMA cipher_compatibility = 3;")
            
            try featureDB.key(key)
            
        } catch let error as NSError {
            MyUtils.Log(TAG, "Unable to create/read my.sqlite: \(error.debugDescription)")
        }
```
This failed to read the SQLite file encrypted with version 3 SQLCipher.

Any ideas welcome.
