### ISSUE TITLE
'UnsafeRawBufferPointer' is not convertible to 'UnsafePointer<_>'

### ISSUE THREAD

**Issue by RockyQu** [stephencelis/SQLite.swift#914]
I used this integration to report this error.

use xcode 10.1 ,swift 4.2

**Comment by Vuong-Dao** [comment]
Yes. I got the issue.

**Comment by sburlewapg** [comment]
Is this the case in `Data.datatypeValue` in `Foundation.swift`? If so, #902 fixed this issue.

**Comment by Vuong-Dao** [comment]
> Is this the case in `Data.datatypeValue` in `Foundation.swift`? If so, #902 fixed this issue.

Hi. Could you check it again? I used the latest update. But the issue is still there

**Comment by sburlew** [comment]
Version 0.11.6 requires Xcode 10.2, so if you’re unable to use that then you’ll probably need to fork 0.11.6 and change that code to the previous version until whenever you can update to Xcode 10.2.

**Comment by RockyQu** [comment]
@Vuong-Dao Xcode upgrade to the latest, using 0.12.0 this version, no more error

**Comment by ypopovych** [comment]
Seems as fixed in the new version

**Comment by Suresh-Alangat** [comment]
This version didn't solve my issue. Shows the same in 0.12.0 also
